### ISSUE TITLE
UI: part action window as a PDA while in EVA

### ISSUE THREAD

**Issue by JonnyOThan** [JonnyOThan/Kerbal-VR#124]
Both from external view and EVA.  Probably just aiming at the part and doing "InteractUI"

- [x] Open PAW from external view
- [x] Open PAW from EVA
- [x] fix z-fighting
- [x] support clicking
- [ ] some z-fighting remains
- [ ] center on the hand
- [x] Make sure non-vr mode works after using the PDA

**Comment by Arbel-arad** [comment]
this could probably be done through RPM with a part list that displays context menu buttons

**Comment by JonnyOThan** [comment]
> this could probably be done through RPM with a part list that displays context menu buttons

If I'm understanding what you mean, that kind of thing already exists in VesselViewer.

**Comment by JonnyOThan** [comment]
I'm gonna call this done, everything else is polish
