### ISSUE TITLE
mk3 cockpit hatch is too far to reach.

### ISSUE THREAD

**Issue by Arbel-arad** [JonnyOThan/Kerbal-VR#137]
the doors in the mk3 plane cockpit are one floor down and 2-3m back from the seats, making them impossible to reach.

**Comment by JonnyOThan** [comment]
Crew EVA can also be done through the target menu on the MFD.  There's nothing stopping you from standing up and moving to reach the levers.  Eventually that will become more immersive with FreeIVA support, but I probably don't plan on changing the IVAs to make sure there's always a handle within reach.
