### ISSUE TITLE
cant do anything inside

### ISSUE THREAD

**Issue by DanPlayzJakov** [JonnyOThan/Kerbal-VR#179]
its almost impossible to flick the switches or press buttons in the mk command pods

**Comment by JonnyOThan** [comment]
Is it *hard* or does it *not work?*. Which IVA are you using?

You might want to try the human hands config instead; the kerbal fingers are pretty fat at the tips which can make things difficult if you’re not used to it.

**Comment by DanPlayzJakov** [comment]
it is very hard, im using the command pod mk1, i tried the command pod mk1-3 still was hard to press anything

**Comment by JonnyOThan** [comment]
Can you be more specific?  Are you using the KSA mk1 pod, the stock one, DE_IVA, something else?  Are there certain props that are harder to interact with than others?

A screenshot would help.

What hardware are you using and how are you connecting it to the PC?  Are you using hand tracking or controllers?

Did you try the human hands config?

**Comment by DanPlayzJakov** [comment]
i am using the oculus quest 2 as my vr headset, all of the props are just as hard to interact with, and i'm using a usb 2.0 connection with to connect with oculus link, i still have yet to try human hands config tho, i am reinstalling the mod so i'll see if that would help

**Comment by DanPlayzJakov** [comment]
alright after reinstalling the mod, it works now, but the stock cockpit does not work, you can barely do anything inside of there.

**Comment by JonnyOThan** [comment]
> the stock cockpit does not work, you can barely do anything inside of there.

Yes, please read the KerbalVR install guide, specifically https://github.com/JonnyOThan/Kerbal-VR/wiki/Installation-Guide#a-note-on-iva-selection
