### ISSUE TITLE
Kerbal eye offset should be consistent

### ISSUE THREAD

**Issue by JonnyOThan** [JonnyOThan/Kerbal-VR#203]
Some users are saying the flightstick and throttle are too close to the camera position, causing “t-Rex arms.”  Especially since female eyes are smaller, we should override the eye offset and make it consistent everywhere.

**Comment by Kam1ni** [comment]
I don't know if the eye offset is the issue here. I think in general everything seems a bit small. All the avionics are tiny and unreadable.

I did find out though for anyone also having this issue that going to the steam vr settings->per application video settings->override world scale and set it to about 125% fixes the issue somewhat. But that's only on IVA. EVA everything seems off. Just the scale of everything seems of but that might be because Kerbals have such tiny boddies and a massive head.

**Comment by JonnyOThan** [comment]
This issue is referring to the fact that different seats in different IVAs have different eye offsets.  These are selected for visibility with the normal IVA mode, but don't make sense in VR.

Many IVA layouts use props at very small scales.  If you're having trouble with scale please include which cockpit and IVA layout you were using.

On top of all that, there was a bug with certain kerbal suits where the entire world would be about half scale, but that's been fixed in the latest release.

**Comment by Kam1ni** [comment]
Oh okay. I missunderstood the issue then. But yeah. There is definitly an issue with scale. I just tested it with all stock and making history cockpits and all af the issue. At least for me. 

Firstly all avionics are small. On the standard sized mfd your kerbal finger is about the size of two buttons. Then you have the position of the stick and throttle. If I reset my camera position. The controls are where my chest is which isn't very usable. When I EVA the ground feels to close to my head. It's at about the height of my belly. So I assume the scale isn't exactly set correct. 

One thing that makes me certain it's worldscale is in some cockpits there are post it notes. In the coupolla there is one very close right in front of you. And it feels like it's only about 50-75% the size of a real one.

**Comment by JonnyOThan** [comment]
Some screenshots might help as well...but please open a new issue for this.  And let me repeat:  If you're having trouble with scale please include which cockpit and IVA layout you were using.  The same MFD can be placed in different cockpits at different scales.

**Comment by Kam1ni** [comment]
Allright. I will in a bit.
