### ISSUE TITLE
[SOLVED] KSP gets closed/crashes when losing the VR "focus"

### ISSUE THREAD

**Issue by jeancallisti** [JonnyOThan/Kerbal-VR#215]
This was observed with a Lenovo Explorer, which was originally designed for Windows Mixed Reality but is supposed to be compatible with Steam VR and OpenXR.

1. Open "KSP with VR". It starts SteamVR
2. Go to the IVA; turn on VR with Alt+V
3. Do **anything that disables VR:** 
    - unplug the headset OR
    - wait long enough for the headset to go to sleep OR
    - in the headset's built-in virtual UI, switch to some other app
**Observed (bad) :** KSP closes entirely. Not sure if it's a crash or an expected behaviour from SteamVR
**Expected (good)** : KSP only reverts to "not VR"; ideally, the VR an be turned on again later.

**Comment by jeancallisti** [comment]
Some advice for the users of WMR-compatible equipment : 

1. Make the Mixed reality Portal start its Steam-compatible version : 
    - Open the Mixed Reality Portal settings
    - In the hamburger menu on the left, click "See More..." --> "Settings"
    - "Startup and desktop"
    - Tick **"Start Windows Mixed Reality for SteamVR automatically when Mixed Reality Portal is launched"**

2. Prevent it from trying to take over when it gains or loses focus of the VR
    - Untick **"Open the desktop view app when a desktop app gains focus..."**
    - Tick "Create virtual displays...."

2. Disable sleep
    - Open the Mixed Reality Portal settings
    - In the hamburger menu on the left, click "See More..." --> "Settings"
    - "Headset display"
    - At the very bottom : TURN OFF "Suspend Windows Mixed Reality and its apps when..."

**Comment by JonnyOThan** [comment]
Thanks for the detailed steps!!

The player.log file and any associated crash .dmp files might be useful if it’s a problem in the kerbalVR code, but given the workaround above it’s probably not worth spending much time on this.
