### ISSUE TITLE
Box appearing inside a module

### ISSUE THREAD

**Issue by Alaska-43** [JonnyOThan/Kerbal-VR#235]
I'm testing the mod with the Kolonization mod and inside the "PMA-4 'Nature' Science lab" a gigant box appears with colisions where the kerbals can't pass that, I'm not sure if this is a issue of this mod or a bug of the Kopernicus mod. 
**To Reproduce**
1. Use the "PMA-4 'Nature' Science lab" in flight mode
2. Click on show interior overall or go first person with IVA
 You will see a big box cutting the module in half and the Kerbal won't be able to pass that box

**Expected behavior**
That box shouldn't show up
**Log**

[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/10413255/KSP.log)

**Screenshots**

![imagen](https://user-images.githubusercontent.com/94760160/212364949-681c6690-7585-4221-a3c3-fa490ba9890f.png)
![imagen](https://user-images.githubusercontent.com/94760160/212365086-8c92b3ea-3ddc-4ddc-b8f8-a85c536e2cd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - KSP Version: 1.12.3.3173
 - VR Hardware: None
 - Kerbal-VR Version:  0.9.0

**Additional context**
I'm also using the "PMA-2 'Quay' Station Core".
EDIT: This also happens on other default modules

**Comment by JonnyOThan** [comment]
I believe this is the internal space for ProbeControlRoom.  This was a bug that was fixed in FreeIva 0.2.5.1
