### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by guccibear90** [JonnyOThan/Kerbal-VR#249]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log**
Attach a copy of the KSP.log file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - KSP Version: [e.g. 1.4.5]
 - VR Hardware: [e.g. Vive]
 - Kerbal-VR Version: [e.g. 3.2.1]

**Additional context**

**Comment by JonnyOThan** [comment]
You didn't fill out any of the information in the bug template.
