### ISSUE TITLE
Rover IVA controls not working

### ISSUE THREAD

**Issue by Kam1ni** [JonnyOThan/Kerbal-VR#272]
**Describe the bug**
There seems to be no way to control the rover in IVA with throttle and stick controls which I assume according to #79 should be working.

**To Reproduce**
1. Create a rover (I used the MK1 Inline cockpit (tested with stock, DE Expansion and KSA IVAs), and RoveMax Model S2 wheels)
2. Lauch
3. Go to IVA
4. Use throttle and stick

**Expected behavior**
Any type of movement. The wheels didn't turn either. I know the craft should work as the arrow keys work fine. Only the IVA controls seem broken. 

**Log**
[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/10819251/KSP.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - KSP Version: 1.12.5
 - VR Hardware: HTC Vive headset with Valve knucles controllers
 - Kerbal-VR Version: 0.9.1.3

**Comment by JonnyOThan** [comment]
Rover controls are hooked up to a specific prop - the yoke from ASET.  The mk2 lander can is the only stock command pod that has this prop.  There's also one in the right-hand seat in ProbeControlRoom.

**Comment by Kam1ni** [comment]
Allright thanks. I wonder if there is a mod that would allow me to bind rover wheel throttle and steering to an axis action group. Or I'll just write a script for it in kOS.

**Comment by Kam1ni** [comment]
Allright thanks. I wonder if there is a mod that would allow me to bind rover wheel throttle and steering to an axis action group. Or I'll just write a script for it in kOS.

**Comment by JonnyOThan** [comment]
Hmm. It might be reasonable to have a switch somewhere in the IVA that toggles between wheel controls and attitude control. But I’ve found that while driving with parallax collisions on, you really want access to both at the same time.
