### ISSUE TITLE
Constant crashing on mun 

### ISSUE THREAD

**Issue by aperson5647** [JonnyOThan/Kerbal-VR#308]
I was trying ksp vr and i got to the mun i landed it was good 10 or so seconds later the game crashes i think oh whatever its fine reload wait like 30 minutes for the game to start go to the craft on the mun and same issue sometimes the game crashes with the little unity window sometimes i completely blackscreen and i just want to be on the mun, my game doesnt lag at all on the mun or on kerbin yet still crashing 

1. Land on mun
2. Wait a few seconds in VR mode
4. Have game crash or PC blackscreen

I expected the game to remain stable

[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/13257915/KSP.log)

Specs: (if it helps at all)

 - GPU: Radeon RX 580 (8GB VRAM)
 - RAM: 16GB
 - CPU: Ryzen 5 2600x
 - OS: Windows 10
 - KSP Version: [1.12.5]
 - VR Hardware: [Quest 2]
 - Kerbal-VR Version: [0.9.3.0]

the game runs fine on kerbin and in orbit 0 crashes yet just being on the surface landed destroys the game

**Comment by JonnyOThan** [comment]
Hi @aperson5647 , please provide your player.log and error.log files.  Please read this to find them: https://gist.github.com/JonnyOThan/04c2074b56f78e56d115621effee30f9

**Comment by JonnyOThan** [comment]
Oh, you also have a lot of mods installed incorrectly.  I recommend wiping your installation clean and starting over with CKAN.

Please try to reproduce this issue with ONLY KerbalVR and its dependencies installed.  If it still occurs, I will investigate.
