### ISSUE TITLE
Game is not loading, stuck on "Not Responding"

### ISSUE THREAD

**Issue by dandoesgithub** [JonnyOThan/Kerbal-VR#317]
**Describe the bug**
Starting the game immediately shows "Not Responding", and it'll stay like that till you close the game. Once you open the logs you will see a bunch of spam "Detected device 1,2, etc."

**To Reproduce**
1. Start the game
2. See error

**Expected behavior**
I expected the game to load without any issues.

**Log**
Note: I had to get rid of some lines (detected device), because that made the file 182 MB, they aren't important to the log since if i kept KSP open it would of kept spamming it
[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/13692059/KSP.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - KSP Version: 1.12.5
 - VR Hardware: Oculus Quest 2
 - Kerbal-VR Version: 0.9.4.0

**Additional context**
Presumably the hardware is connecting over and over again

**Comment by JonnyOThan** [comment]
Fixed in https://github.com/JonnyOThan/Kerbal-VR/commit/345834d0dcd86a84388c5a1b44d2cad120f03e00
