### ISSUE TITLE
prop monitors Become really small

### ISSUE THREAD

**Issue by Cyanide719** [JonnyOThan/Kerbal-VR#89]
**Describe the bug**

**To Reproduce**
1. Go to 'Kerbal Vr mk1 planes cockpit'
2. Click on 'view'
3. See error

**Expected behavior**
I expected the prop monitors to be way bigger I went to you're twitch showcase and saw the size [difference.]

**Log**
Attach a copy of the KSP.log file.
[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/9268660/KSP.log)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - KSP Version: [1.12.3]
 - VR Hardware: [Quest 2]
 - Kerbal-VR Version: [0.50]

**Additional context**

**Comment by JonnyOThan** [comment]
I think the scale on the props in the KSA IVAs is just off

**Comment by JonnyOThan** [comment]
https://github.com/JonnyOThan/KSA-IVA-Upgrade/issues/3
